branch-defaults:
  master:
    environment: jwtAuthserver-env
  seed:
    environment: jwtAuthserver-env
deploy:
  artifact: dist/deploy.zip
global:
  application_name: jwt-authserver
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-east-1
  profile: saml
  sc: git
